project:
  type: website
  output-dir: _site
 

website:
  title: "User-Driven Audits Research"
  cookie-consent: false
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
      showHighlights: true
  page-footer: | 
    This is a website of the Human-Interaction Institute at Carnegie Mellon University (2023)
  navbar:
    background: light
    search: false
    left:
      - href: index.qmd
        text: Home
      - text: "Team"
        file: about.qmd
      - text: "Papers"
        file: papers.qmd
      - text: "Software"
        file: software.qmd
      - text: "Data"
        file: data.qmd
      - text: "Graphics"
        file: graphics.qmd


format:
  html:
    theme: lux
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    linkcolor: black
    email-obfuscation: javascript 
    backgroundcolor: white

callout-appearance: simple



  



